name: Build and release

on:
  push:
    branches:
      - "*"

jobs:
  release-package:
    runs-on:
      group: windows-runner

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main

      - name: Debug release outputs
        run: |
          echo "releases_created: ${{ steps.release.outputs.releases_created }}"
          echo "version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore -p:Deterministic=true
          tree
      - name: Pack
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: |
          dotnet pack --configuration Release --no-build

